default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_para_testes_postgresql_development

test:
  <<: *default
  database: app_para_testes_postgresql_test

production:
  <<: *default
  database: app_para_testes_postgresql_production
  username: app_para_testes_postgresql
  password: <%= ENV['APP_PARA_TESTES_POSTGRESQL_DATABASE_PASSWORD'] %>
